// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Nicholas Phillips

package controlplane_test

import (
	"context"
	"errors"
	"strings"
	"testing"

	cp "github.com/burrow-cloud/burrow/controlplane"
)

// The engine tests for giving a second person access (ADR-0084 §2).
//
// The property every one of these is about: WHAT TRAVELS IS NOT WHAT IS CARRIED. An invitation
// expires, is spent on first use, and cannot authenticate anything; the credential it exchanges for
// is generated by the exchange, which happens on the recipient's own machine.

// TestInviteIssuesSomethingThatIsNotACredential is the shape of the whole feature: an admin gets
// back an invitation, and an invitation is marked as one, expires, and is for the invited principal
// rather than for the admin.
func TestInviteIssuesSomethingThatIsNotACredential(t *testing.T) {
	ctx := context.Background()
	e, _, clock := newIdentityEngine(t)

	admin, _, err := e.ClaimFirstPrincipal(ctx, "operator")
	if err != nil {
		t.Fatalf("ClaimFirstPrincipal: %v", err)
	}

	invited, issued, err := e.InvitePrincipal(ctx, callerFor(admin), "ada", false)
	if err != nil {
		t.Fatalf("InvitePrincipal: %v", err)
	}
	if invited.Name != "ada" || invited.ID == admin.ID {
		t.Fatalf("invited = %+v, want a new principal named ada", invited)
	}
	if invited.Admin {
		t.Error("invited principal is an admin without --admin having been asked for")
	}
	if !issued.Credential.Enrollment {
		t.Error("what came back is not marked as an invitation, so it would authenticate every route (ADR-0084 §2)")
	}
	if issued.Credential.PrincipalID != invited.ID {
		t.Errorf("invitation belongs to %q, want the invited principal %q", issued.Credential.PrincipalID, invited.ID)
	}
	if want := clock.Now().Add(cp.DefaultInvitationTTL); !issued.Credential.ExpiresAt.Equal(want) {
		t.Errorf("invitation expires at %v, want %v — an invitation always expires", issued.Credential.ExpiresAt, want)
	}
	if issued.Token == "" {
		t.Error("no invitation token to hand over")
	}
}

// TestOnlyAnAdminInvites: inviting somebody is how a person who is not on the cluster gets access at
// all, so it is the decision the admin bit exists for (ADR-0084 §2).
func TestOnlyAnAdminInvites(t *testing.T) {
	ctx := context.Background()
	e, _, _ := newIdentityEngine(t)

	admin, _, err := e.ClaimFirstPrincipal(ctx, "operator")
	if err != nil {
		t.Fatalf("ClaimFirstPrincipal: %v", err)
	}
	ada, err := e.CreatePrincipal(ctx, callerFor(admin), "ada", false)
	if err != nil {
		t.Fatalf("CreatePrincipal: %v", err)
	}

	if _, _, err := e.InvitePrincipal(ctx, callerFor(ada), "bob", false); !errors.Is(err, cp.ErrForbidden) {
		t.Fatalf("a non-admin invite = %v, want ErrForbidden", err)
	}
	// And the shared install token, which names nobody at all.
	if _, _, err := e.InvitePrincipal(ctx, cp.Caller{}, "bob", false); !errors.Is(err, cp.ErrForbidden) {
		t.Fatalf("an unauthenticated invite = %v, want ErrForbidden", err)
	}
}

// TestReInvitingSomebodyIssuesAnotherInvitationAndNotAPromotion: an expired invitation has to be
// re-issuable, and re-issuing must not be a way to hand somebody the admin bit they were not given.
func TestReInvitingSomebodyIssuesAnotherInvitationAndNotAPromotion(t *testing.T) {
	ctx := context.Background()
	e, _, _ := newIdentityEngine(t)

	admin, _, err := e.ClaimFirstPrincipal(ctx, "operator")
	if err != nil {
		t.Fatalf("ClaimFirstPrincipal: %v", err)
	}
	first, firstInvite, err := e.InvitePrincipal(ctx, callerFor(admin), "ada", false)
	if err != nil {
		t.Fatalf("first InvitePrincipal: %v", err)
	}

	again, secondInvite, err := e.InvitePrincipal(ctx, callerFor(admin), "ada", true)
	if err != nil {
		t.Fatalf("second InvitePrincipal: %v", err)
	}
	if again.ID != first.ID {
		t.Errorf("re-inviting recorded a second principal (%q, was %q); one person is one identity", again.ID, first.ID)
	}
	if again.Admin {
		t.Error("re-inviting with --admin promoted an existing principal; an invitation is a way in, not a promotion")
	}
	if secondInvite.Token == firstInvite.Token {
		t.Error("the second invitation is the same string as the first")
	}
}

// TestInvitingARevokedPrincipalIsRefused: nothing issued to a retired principal would authenticate,
// so an invitation for one is a link that cannot work and the refusal says so instead.
func TestInvitingARevokedPrincipalIsRefused(t *testing.T) {
	ctx := context.Background()
	e, db, clock := newIdentityEngine(t)

	admin, _, err := e.ClaimFirstPrincipal(ctx, "operator")
	if err != nil {
		t.Fatalf("ClaimFirstPrincipal: %v", err)
	}
	ada, err := e.CreatePrincipal(ctx, callerFor(admin), "ada", false)
	if err != nil {
		t.Fatalf("CreatePrincipal: %v", err)
	}
	if err := db.RevokePrincipal(ctx, ada.ID, clock.Now()); err != nil {
		t.Fatalf("RevokePrincipal: %v", err)
	}

	_, _, err = e.InvitePrincipal(ctx, callerFor(admin), "ada", false)
	if !errors.Is(err, cp.ErrInvalid) {
		t.Fatalf("inviting a revoked principal = %v, want ErrInvalid", err)
	}
	if !strings.Contains(err.Error(), "revoked") {
		t.Errorf("refusal = %q, want it to name the revocation", err)
	}
}

// TestRedeemingAnInvitationMakesTheCredentialHereAndSpendsTheInvitation is the exchange: the caller
// gets a credential that authenticates, and the invitation they presented stops working.
func TestRedeemingAnInvitationMakesTheCredentialHereAndSpendsTheInvitation(t *testing.T) {
	ctx := context.Background()
	e, _, _ := newIdentityEngine(t)

	admin, _, err := e.ClaimFirstPrincipal(ctx, "operator")
	if err != nil {
		t.Fatalf("ClaimFirstPrincipal: %v", err)
	}
	_, invite, err := e.InvitePrincipal(ctx, callerFor(admin), "ada", false)
	if err != nil {
		t.Fatalf("InvitePrincipal: %v", err)
	}

	// The recipient's side starts exactly where a request does: with the token they were sent.
	caller, err := e.AuthenticateCredential(ctx, invite.Token)
	if err != nil {
		t.Fatalf("authenticating the invitation: %v", err)
	}
	if !caller.Enrollment {
		t.Fatal("the caller behind an invitation is not marked as one, so it would reach every route")
	}

	_, issued, err := e.RedeemInvitation(ctx, caller)
	if err != nil {
		t.Fatalf("RedeemInvitation: %v", err)
	}
	if issued.Token == invite.Token {
		t.Fatal("the exchange handed back the invitation itself; the credential must be made here, not forwarded")
	}
	if issued.Credential.Enrollment {
		t.Error("the credential the exchange returned is itself an invitation")
	}
	if !issued.Credential.ExpiresAt.IsZero() {
		t.Errorf("the exchanged credential expires at %v; a person's own credential does not expire on its own",
			issued.Credential.ExpiresAt)
	}
	if issued.Credential.Kind != cp.CredentialKindUser {
		t.Errorf("exchanged credential kind = %q, want %q", issued.Credential.Kind, cp.CredentialKindUser)
	}

	// It authenticates, as the same person the invitation named.
	after, err := e.AuthenticateCredential(ctx, issued.Token)
	if err != nil {
		t.Fatalf("authenticating the exchanged credential: %v", err)
	}
	if after.PrincipalID != caller.PrincipalID {
		t.Errorf("exchanged credential is for %q, want the invited principal %q", after.PrincipalID, caller.PrincipalID)
	}
	if after.Enrollment {
		t.Error("the exchanged credential still reads as an invitation")
	}

	// And the invitation is spent: a second holder of the same string gets nothing.
	if _, err := e.AuthenticateCredential(ctx, invite.Token); !errors.Is(err, cp.ErrForbidden) {
		t.Fatalf("the spent invitation still authenticates (%v); an invitation is exchangeable once", err)
	}
}

// TestOnlyAnInvitationCanBeExchanged: the exchange is not a way for anybody holding a credential to
// mint themselves another. What authorizes it is the invitation, and a caller without one has
// nothing to spend.
func TestOnlyAnInvitationCanBeExchanged(t *testing.T) {
	ctx := context.Background()
	e, _, _ := newIdentityEngine(t)

	admin, issued, err := e.ClaimFirstPrincipal(ctx, "operator")
	if err != nil {
		t.Fatalf("ClaimFirstPrincipal: %v", err)
	}
	caller, err := e.AuthenticateCredential(ctx, issued.Token)
	if err != nil {
		t.Fatalf("AuthenticateCredential: %v", err)
	}

	_, _, err = e.RedeemInvitation(ctx, caller)
	if !errors.Is(err, cp.ErrInvalid) {
		t.Fatalf("exchanging an ordinary credential = %v, want ErrInvalid", err)
	}
	if !strings.Contains(err.Error(), admin.Name) {
		t.Errorf("refusal = %q, want it to say who is already signed in", err)
	}

	if _, _, err := e.RedeemInvitation(ctx, cp.Caller{}); !errors.Is(err, cp.ErrForbidden) {
		t.Fatalf("exchanging with no authenticated caller = %v, want ErrForbidden", err)
	}
}
